/*
 * IntrinsicMakros.h
 *
 *  Created on: Oct 18, 2010
 *      Author: Simon Moll
 */

#ifndef INTRINSICMAKROS_HPP_
#define INTRINSICMAKROS_HPP_

#define CONST_FUNC(INTRINSIC,RETURN,ACTUAL,ARGS,ARGC) \
	const RETURN INTRINSIC ARGS __attribute__((const));

#define FUNC(INTRINSIC,RETURN,ACTUAL,ARGS,ARGC) \
	const RETURN INTRINSIC ARGS;

#define COMPLEX(INTRINSIC,RETURN,FORMAT,ARGS) \
	const RETURN INTRINSIC ARGS __attribute__((const));

#define CONST_COMPLEX(INTRINSIC,RETURN,FORMAT,ARGS) \
	const RETURN INTRINSIC ARGS;

#define INFIX(OP,RETURN,INTRINSIC,ARGS) \
	const RETURN INTRINSIC ARGS;

#define NATIVE(NAME) \
		class NAME;

#define INTERP(NAME,RETURN,ARGS)\
		const RETURN NAME ARGS;

#define PASS(RETURN,INTRINSIC,ARG)\
		const RETURN INTRINSIC ARG;

#define BUILTIN(TYPE,INTRINSIC,ACTUAL) \
		extern TYPE INTRINSIC;

#define GETTER(NAME,TYPE,ARGUMENT) \
		const TYPE NAME ARGUMENT;

#define SETTER(NAME,ARGUMENT) \
		void NAME ARGUMENT;

#define REPLACE_FUNC(NAME,RETURN,REPLACEMENT) \
		const RETURN NAME();

#define MUTE(X)


#endif /* INTRINSICMAKROS_HPP_ */
