##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

PARALLEL_DIRS=axtor axtor_ocl axtor_glsl

include $(LEVEL)/Makefile.common
