##===- projects/sample/lib/sample/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=Axtor_GLSL
# SHARED_LIBRARY = 1
# ARCHIVE_LIBRARY = 1

# USEDLIBS=

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
