/*
 * OCLEnum.h
 *
 *  Created on: 25 Jan 2012
 *      Author: v1smoll
 */

#ifndef OCLENUM_H_
#define OCLENUM_H_

#include <llvm/IR/Value.h>

namespace axtor {

	// returns the string representation of a mem_fence..enum generated by the OpenCL Frontend
	bool evaluateEnum_MemFence(llvm::Value * value, std::string & result);

	// returns the string representation of a sampler_t enum generated by the OpenCL Frontend
	bool evaluateEnum_Sampler(size_t cfg, std::string & result);
}

#endif /* OCLENUM_H_ */
