##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=axtorOCLDriver oclang axtorIntrinsicHeaders
# extractor

# Has only been tested on Linux. Disable for other OSes

include $(LEVEL)/Makefile.common
